services:
  db:
    image: mysql:8.4
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - laravel

  redis:
    image: redis:7.4.1-alpine
    container_name: laravel-redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--save", "60", "10000", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - laravel

  nginx:
    image: nginx:1.27.2-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - app-data:/var/www
      - ./docker/storage_app:/var/www/storage/app
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/nginx/logs:/var/log/nginx/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
    
volumes:
    laravel-redis:
        driver: local
    app-data: