name: Build & Deploy to Stage

on:
  push:
    branches:
      - master
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.3
            experimental: true
            composer_args: "--optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs --no-scripts"

    steps:
      - name: Deploy to stage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin master
            docker compose pull
            docker compose down
            docker volume rm laravel-ulem_app-data
            docker compose up -d
            sleep 10
            bash entrypoint.sh