name: Build & Deploy to Stage

on:
  push:
    branches:
      - master
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.3
            experimental: true
            composer_args: "--optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs --no-scripts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl, zip, gd, pdo_mysql, opcache, pcntl, bcmath, sockets, exif, imagick, redis, apcu, memcached, mongodb

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: |
          php -v
          composer -V
          cp .env.example .env
          composer install
        env:
          COMPOSER_CACHE_DIR: /var/www/caches/composer_cache

      - name: Setup Laravel
        run: |
          php -v
          php artisan --version
          php artisan about

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OWNER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/deploy/production/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/laravel-ulem:latest

      - name: Deploy to stage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin master
            docker compose pull
            docker compose down
            docker volume rm laravel-ulem_app-data
            docker compose up -d
            sleep 10
            bash entrypoint.sh